### ISSUE TITLE
Entire set of GO-CAM models

### ISSUE THREAD

**Issue by eranbio** [geneontology/noctua-models#147]
Hello,
Linking to the models directory we get a message that:
"Sorry, we had to truncate this directory to 1,000 files. 2,766 entries were omitted from the list."
So where can I find and download the full set of models?

Eran

**Comment by balhoff** [comment]
You can use the `git` command to clone this repository:

`git clone git@github.com:geneontology/noctua-models.git`

Or if you don't want to use `git`, you can directly download a zip: https://github.com/geneontology/noctua-models/archive/master.zip

**Comment by eranbio** [comment]
Thanks! Sorry for the late response
