### ISSUE TITLE
Lets add the reactome models into the master collection

### ISSUE THREAD

**Issue by goodb** [geneontology/noctua-models#163]
It would be useful for a number of reasons (manuscript writing, grant writing, kg-covid, go-cam related bioinformatics research) to have the current version of the go-cams generated from the Reactome models accessible in a stable, public location.  

Curators and software should be aware that these models are 'development' status as their metadata indicates and should be treated as such.  

If yes, the PR is ready to go.  
https://github.com/geneontology/noctua-models/pull/162

**Comment by balhoff** [comment]
I think this has been done, since the PR is merged.
