### ISSUE TITLE
model 57c4867e00000002 does not parse 

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua-models#18]
this is breaking http://build.berkeleybop.org/job/export-lego-to-legacy/

```
~/repos/noctua-models(master) $ owltools --catalog-xml fake-catalog.xml  models/57c4867e00000002 
2016-09-21 16:27:46,951 INFO  (ParserWrapper:75) Start loading ontology: file:/Users/cjm/repos/noctua-models/models/57c4867e00000002 from: file:/Users/cjm/repos/noctua-models/models/57c4867e00000002
2016-09-21 16:27:47,257 INFO  (ParserWrapper:75) Start loading ontology: http://purl.obolibrary.org/obo/go/extensions/go-lego.owl from: file:/Users/cjm/repos/noctua-models/fake-go-lego.owl
2016-09-21 16:27:47,272 INFO  (ParserWrapper:82) Finished loading ontology: http://purl.obolibrary.org/obo/go/extensions/go-lego.owl from: file:/Users/cjm/repos/noctua-models/fake-go-lego.owl
2016-09-21 16:27:47,276 INFO  (ParserWrapper:82) Finished loading ontology: null from: file:/Users/cjm/repos/noctua-models/models/57c4867e00000002
2016-09-21 16:27:47,277 ERROR (CommandRunner:4113) could not parse:models/57c4867e00000002
org.semanticweb.owlapi.model.OWLRuntimeException: Prefix not registered for prefix name: :
```

**Comment by cmungall** [comment]
looks like the cause:

```
Class: <IDA>

    Annotations: 
        
            Annotations: <http://geneontology.org/lego/derived> "true"^^xsd:string
        <http://www.geneontology.org/formats/oboInOwl#id> "IDA"^^xsd:string
```

Note the `<IDA>`. This is only valid if there is a default `:`.

Super bizarre how this model got into this state. It's like the OWLAPI got confused about prefixes. This looks potentially like a variant of https://github.com/owlcs/owlapi/issues/537

**Comment by kltm** [comment]
Depends on how you cut it, but I think that somebody got around the evidence code input and just let it fly with the three letter string. I recall something similar at the training.
The client should do a better job of pre-check, the server should choke on the bad input.

**Comment by kltm** [comment]
Yes, not quite the same thing, but somebody got through using a string instead of selecting an ID for gene products; made the model unparsable:
```
      Error (error): Could not successfully handle batch
      request. Exception:
      org.semanticweb.owlapi.model.OWLRuntimeException. Prefix not
      registered for prefix name: :; your operation was likely not
      performed.
```

**Comment by ukemi** [comment]
Should I try to fix this model or are we going to use it for a QC check. Any way we can have the production models as a separate job, so development models won't be show stoppers?

**Comment by cmungall** [comment]
My PR replaces the string with the ECO class, but I see there is a conflict now - so someone maybe tried to fix it in the UI.

**Comment by cmungall** [comment]
> Any way we can have the production models as a separate job, so development models won't be show stoppers?

No need for a separate job. This should never happen, dev or production. You did nothing wrong.

**Comment by ukemi** [comment]
The model UI still has an IDA in the left-most individual.

**Comment by balhoff** [comment]
Also:

```
$ grep '<[^h]' models/*
models/57c4867e00000002:Class: <IDA>
models/57c4867e00000002:        <IDA>
models/57c82fad00000451:Class: <Q62765>
models/57c82fad00000451:Class: <Q63373>
models/57c82fad00000451:        <Q63373>
models/57c82fad00000451:        <Q62765>
```

**Comment by kltm** [comment]
Okay, I just pulled in the last model set and restart the server--we're now getting the badness as described here: https://github.com/geneontology/noctua-models/issues/18#issuecomment-248775569

**Comment by kltm** [comment]
Different model fixed by https://github.com/geneontology/noctua-models/pull/21
