### ISSUE TITLE
In noctua-model TTLs, change all ORCIDs used for GO from HTTP to HTTPS

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua-models#194]
Currently, there is a mix of HTTP and HTTPS used for the scheme in URIs for user ORCIDs--some due to user.yaml inconsistency and upstream data. After some discussion we have decided to convert all of our noctua-models to be just HTTPS after https://github.com/geneontology/go-site/issues/1708 is completed and restart the systems, fixing any problems that come up.

We'll do this in two stages: 1) apply to noctua-models `dev` and then 2) apply to noctua-models `master`. We'll hopefully work out all the kinks on 1.

**Comment by vanaukenk** [comment]
Still moving ahead with plan to update production models on Thursday, July 20th.  
One anomaly I noticed on noctua-dev is that I had one model with two (!) titles and it didn't get an http -> https update.
Not sure whether we need to be concerned about this on production, but thought I would note that here anyway.

**Comment by kltm** [comment]
I believe this cleared w/o fanfare some time ago?
Please reopen if I'm mistaken.
