### ISSUE TITLE
Protein isoform identifiers-> (ref: gomodel:5993df9e00000254)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#36]
Is there a way to make annotations to specific protein isoforms in Noctua?

E.g. Figures 1d and 1f in PMID:24121663 show that isoforms _alpha_ (UniProt ID O15350-1) and _beta_ (UniProt ID O15350-2) of TP73, which contain a transactivation domain [but not isoform _dN-alpha_ (UniProt ID O15350-8), which lacks this domain] regulate the expression of _GLS2_. 

However, when I try to add O15350-2 to my model, it allows me to select only the 'parent' UniProt ID O15350, and not a specific isoform ID.

Is there a way to make isoform-specific annotations in Noctua, or do I need to use Protein2GO to capture the information about specific isoforms?

(ref: http://noctua.berkeleybop.org/editor/graph/gomodel:5993df9e00000254)

cc: @RLovering

**Comment by cmungall** [comment]
Ah, I see what's happening here. You should have the ability to use any entity that is in your species gpi file.

However, unfortunately the goa files operate differently than other species. In particular, there are *two* GPIs produced, one for gene-level / reference / GCRP entities, the other for isoforms.

I was aware of the split for GAF/GPAD (I still think this needlessly complicates things and these should be in the same GAF, with the GCRP in col2 and the isoform in c17 where present, see https://github.com/geneontology/go-site/issues/185 for more of my moaning to @tonysawfordebi here). I had somehow neglected to remember this when specifying the pipeline for GPIs (it's there in the [goa metadata file](https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml) so I have no excuse).

We made the assumption that each species would have max one GPI, I will go ahead and revise this assumption. Unfortunately you'll have to wait for up to a week.

**Comment by cmungall** [comment]
OK, changed the configuration to include isoform (so we now have all 4: GCRP, complex, rna and isoform). 

The build was successful:
https://build.berkeleybop.org/job/build-noctua-entity-ontology/lastSuccessfulBuild/

This will be visible next time minerva restarts and solr reloads, I think this w/e

**Comment by kltm** [comment]
If this requires a minerva restart, that's a manual operation. I'll pencil it in for Friday. Let me know if you want that done sooner.

**Comment by BarbaraCzub** [comment]
Thank you @cmungall and @kltm . This weekend will be fine. I'll come back to this model next week.

**Comment by BarbaraCzub** [comment]
I just tried searching for UniProt isoform IDs: 'O15350-1' or 'O15350-2' in Noctua, but still only the 'parent' protein ID (O15350) appears to be available. I suppose this minerva restart has not happened yet?

**Comment by kltm** [comment]
This issue was moved to geneontology/noctua#486
