### ISSUE TITLE
Is there a way to select several individuals and move them together? (ref: gomodel:586fc17a00001446)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#38]
Is there a way to select a few individuals and annotons in a model to move them around the canvas as a group?

E.g. when a new annoton is added to an exiting model, it usually appears at the far rhs of the canvas. If a few annotons and individuals are added sequentially, and then I want to move them to the area of the canvas where I can see most of the annotons and individuals added earlier, is there a way to select the new ones and move them on the canvas all together as a group? Or can they only be moved one by one (which is what I have been doing so far)?

(optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00001446)

**Comment by kltm** [comment]
This issue was moved to geneontology/noctua#479

**Comment by kltm** [comment]
@BarbaraCzub This is a question about the software, not the model or annotation, so has been moved.
