### ISSUE TITLE
Noctua GO terms update? (ref: gomodel:586fc17a00001446)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#39]
I have just noticed that although the GO term name of GO:0006900 was changed from 'membrane budding' to 'vesicle budding from membrane' over a month ago, the term is still displayed as 'membrane budding' in my model (screenshots below) (I added it today). Have some updates not gone through?

<img width="869" alt="screen shot 2017-08-25 at 17 48 33" src="https://user-images.githubusercontent.com/16541096/29723875-319fd622-89be-11e7-90c4-44a87fc3ba62.png">

<img width="294" alt="screen shot 2017-08-25 at 17 52 10" src="https://user-images.githubusercontent.com/16541096/29723868-29fe09fc-89be-11e7-971c-d628f845d03b.png">

cc: @RLovering 

 (optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00001446)

**Comment by kltm** [comment]
This issue was moved to geneontology/noctua#480

**Comment by kltm** [comment]
@BarbaraCzub This is a question about the software, not the model or annotation, so has been moved.
