### ISSUE TITLE
How to delete a model? -> (ref: gomodel:598826eb00000261)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#42]
How do I delete this model?

I previously changed its state to 'delete' and marked it as 'Deprecated', but when I logged into Noctua this morning the state for this model was displayed as 'development' again.

I will not be doing any more work on this model, hence I marked it as 'delete', and made a new one instead (gomodel:598826eb00000503).

 (optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:598826eb00000261)

cc: @RLovering

**Comment by kltm** [comment]
This issue was moved to geneontology/noctua#485

**Comment by kltm** [comment]
@BarbaraCzub Non-model specific issues and software issues should be in the noctua tracker, not the noctua-models tracker.

**Comment by kltm** [comment]
That is all you need to do. At some future date a purging process will be added, as well as a default of hiding them, but in general curators can only request the delete.
In some cases, we may choose to manually destroy a model immediately, but that will be rare.

**Comment by BarbaraCzub** [comment]
How do I know whether this is a model-specific issue, or not?

For this specific model I had previously marked it as 'delete' and 'depreciated' but its state still became reverted back to 'development' (when I intended for it to be deleted). 

I have no way of knowing whether the issue is model-specific, or affects Noctua overall.

However, I previously started developing a model, entitled: 'SynGO no. 1b SGT-CSP1-HSC70_PMID:11580898', which is nowhere to be found, when I log into Noctua, and I never marked this one as 'delete'. And I am not suggesting that it should be reinstated (because the authors never confirmed the species to me, so I would not be able to continue working on it), but I probably should have received some notification, when it was being deleted. After all it was in the 'development' state, and _not_ the 'delete' state. 

So perhaps the case of the missing model should have been a hint to me that this _'delete' [changed back to] 'development'_ issue is indeed (similarly?) a Noctua-wide issue, but I simply do not know. (Something could have happened just to one model).

cc: @RLovering

**Comment by kltm** [comment]
@BarbaraCzub If it helps, if it looks like a *mechanism* issue, that's the Noctua tracker; if it is a question about modeling, that would be in this tracker.

**Comment by kltm** [comment]
A discussion of delete and reversion issues can be found from here: https://github.com/geneontology/noctua/issues/485#issuecomment-326360858

**Comment by BarbaraCzub** [comment]
ok, thanks.
