### ISSUE TITLE
why is Noctua inferring an MF from the process the gene is annotated to

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua-models#45]
I was wondering why Noctua is creating an MF that seems to be inferred from the BP the gene is annotated to.

See:
ID - gomodel:59b38c1100000155 
Name - TEST: assuming ND evidence, F-P link directionality - KRC 
http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000155

In the model section using the Ift172 gene, I have only associated Ift172 with an anonymous MF that is part_of the BP term 'smoothened signaling pathway'. However, in the annotation preview, the MF annotation for this gene is for 'signal transducer activity':

**Ift172 Mmus | enables | signal transducer activity** 
Ift172 Mmus | involved_in | smoothened signaling pathway 
Ift172 Mmus | involved_in | cardiac septum morphogenesis 

I don't want this MF annotation. I also don't understand how it can be assumed that all MFs that are part of 'smoothened signaling pathway' are automatically 'signal transducer activity'.

@ukemi suggested that we should get input from @dosumis on this.

**Comment by balhoff** [comment]
'signal transducer activity' ==  molecular_function and (part_of some 'signal transduction')
'cell surface receptor signaling pathway' is_a 'signal transduction'
'smoothened signaling pathway' is_a 'cell surface receptor signaling pathway'

**Comment by ValWood** [comment]
not all parts of signalling pathways are signal transducers. Many molecules are scaffolds, for example.

**Comment by dosumis** [comment]
IIRC, this axiom has been in GO since before I arrived:

'signal transducer activity' == molecular_function and (part_of some 'signal transduction')

> not all parts of signalling pathways are signal transducers. Many molecules are scaffolds, for example.

Can you give some more criteria about what makes something a signal transducer in addition to being part of an ST pathway?  With this we may be able to tighten the def.

Isn't it possible to perform a scaffolding (protein binding bridging?) function in ST and still be considered a signal transducer?

e.g, wouldn't axin and dsh both be considered signal transducers here:

![image](https://user-images.githubusercontent.com/112839/30577961-52be4704-9d09-11e7-9630-9019f6fa3f68.png)

**Comment by ValWood** [comment]
I have never been sure. It was one of my questions for the signalling meeting.

For example ahk1
http://preview.pombase.org/gene/SPAC7D4.03c
http://preview.pombase.org/gene/SPCC1739.11c
http://preview.pombase.org/gene/SPBC32H8.07

are signalling complex scaffolds. They have no catalytic activity? (often WD repeat proteins)

**Comment by ValWood** [comment]
I have a bit of a problem with the term "signal transducer"
It gives us multiple ways of describing the same  molecular function.

GTPase + signal transducer
protein kinase + signal transducer
Therefore we all have lots of 'signal transducers" that aren't described as signal transducers.

I wonder if it is a term we could manage without. 
Or if it should be a parent of all "signal transducers". No point in having concurrent terms to describe the same activity.

BUT, not all GTPAses are signalling transducers, so  you would need
"signal transducing GTPase activity"

**Comment by dosumis** [comment]
> For example ahk1
> http://preview.pombase.org/gene/SPAC7D4.03c
> http://preview.pombase.org/gene/SPCC1739.11c
> http://preview.pombase.org/gene/SPBC32H8.07

> are signalling complex scaffolds. They have no catalytic activity? (often WD repeat proteins)

So catalytic activity is important (necessary) to being a signal transducer?  We classify receptors as signal transducers and some of those (frizzled) have no known catalytic activity.

> I have a bit of a problem with the term "signal transducer" It gives us multiple ways of describing the same molecular function.

We have multi-inheritance classification throughout GO and including in MF. I don't see a problem here if we can pin down a logical def.

> BUT, not all GTPAses are signalling transducers, so you would need
"signal transducing GTPase activity"

Not necessarily. If all GTPases that are part of ST pathways are signal transducers, we can infer classification under signal transducer activity, in fact we would right now from:

'signal transducer activity' == molecular_function and (part_of some 'signal transduction')

I've been playing with formal definitions of 'molecular transducer activity'.  We may be able to tighten up the definition to:

'signal transducer activity' == 'molecular transducer activity' and (part_of some 'signal transduction')

**Comment by cmungall** [comment]
This issue was moved to geneontology/go-ontology#14232
