### ISSUE TITLE
GPAD location

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/noctua-models#49]
Where can I find the GPADs that are generated from Noctua models?

**Comment by balhoff** [comment]
Here are the files generated by the old code: https://build.berkeleybop.org/job/export-lego-to-legacy/lastSuccessfulBuild/artifact/legacy/gpad/

Here are the files generated by the new reasoner: https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/

**Comment by tonysawfordebi** [comment]
Thanks!

**Comment by tonysawfordebi** [comment]
Is it possible to have one GPAD per contributing group that amalgamates all annotations from all models?

**Comment by balhoff** [comment]
This is coming but it's kind of held up by a few dependencies: https://github.com/geneontology/noctua/issues/418

I think @cmungall had an idea of how to proceed without waiting on https://github.com/geneontology/neo/issues/17 ?

**Comment by cmungall** [comment]
See also https://github.com/geneontology/go-site/issues/431

**Comment by tonysawfordebi** [comment]
I've just noticed that all of the GPAD files have "!gpa-version: 1.2" as their header; shouldn't this be "!gpa-version: 1.1"?
The current GPAD format version is 1.1, while the current GPI version is 1.2

**Comment by balhoff** [comment]
Not sure about the version—I copied that from the format produced by Heiko's older code.
