### ISSUE TITLE
Annotating regulation and making regulation_of terms on the fly -> (ref: gomodel:59dc728000000324)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#50]
Hello,

I am seeking advice re: capturing regulation in Noctua and making new regulation terms in GO and/or in Noctua on the fly.

It was decided at the GOC meeting in Cambridge that for assertions of type “Gene product involved_in regulation of X”, we will use default ‘involved in’ ([1](https://docs.google.com/document/d/1Y9_Mvqes3op36TPHgfaS7K5FHnGZLgUApghIFYyUKR8/edit#), [2](https://github.com/geneontology/go-annotation/issues/1687)).

It was also decided that Noctua will create regulation_of GO terms on the fly based on 'regulates' relations in GO-CAM ([1](https://docs.google.com/document/d/1Y9_Mvqes3op36TPHgfaS7K5FHnGZLgUApghIFYyUKR8/edit#heading=h.b17i2exk7sf2)). 
I was wondering whether this has started being implemented yet? 
I recently intended to create two new regulation_of GO terms ([3](https://github.com/geneontology/go-ontology/issues/14361), [4](https://github.com/geneontology/go-ontology/issues/14360)) based on [PMID:17139249](https://www.ncbi.nlm.nih.gov/pubmed/17139249), but during an ontology call I was advised to annotate in Noctua instead. The initial advice was to use the relation causally_upstream_of_or_within but I have since then re-read the paper, and I think it should actually be 'regulates'. (Or part_of regulation_of GO term??). Details below.

### Issue 1: Making regulation_of terms of the fly

I have started making the model, but I noticed that the regulation_of terms do not get created based on the 'regulates' relations, as I expected. Instead the GPAD output uses what would have been the is_a regulation_of parent term, of either of the terms that I intended to create (please compare the screenshots below).

GO-CAM:
![screen shot 2017-11-13 at 11 54 26](https://user-images.githubusercontent.com/16541096/32725877-bfff4e68-c86e-11e7-977d-228a310785f9.png)

Info that goes into the GPAD file:
![screen shot 2017-11-13 at 11 55 27](https://user-images.githubusercontent.com/16541096/32725884-c86b105a-c86e-11e7-8b98-1d7dfe8ad9b2.png)

### Issue 2: 'Regulates' relation + 'MF/BP X'   or   'part_of' relation + 'regulation of MF/BP X'?

Relating to the above, I have just checked the GO-CAM documentation for [regulation_of models](https://docs.google.com/document/d/18ihslb7prB6CWtu2yjF-pMHZBTY1-AdXJAu-ZyuyXS4/edit#heading=h.lg6r9yweazb5). This document actually recommends using part_of relations + regulation_of GO terms. I suppose this is probably out of date?

### Issue 3: Making relations between MF and regulated MF/BP or BP that the MF is part_of and regulated MF/BP --> annotation output very different

The reason why I wanted to take a look at the GO-CAM documentation in the first place was that I seem to recall from a Noctua training that the 'regulates' relation should only be used between molecular functions/activities (here 'protein serine/threonine kinase activity') and the biological processes, which they regulate (here 'dynein intermediate chain binding'). However, if the molecular function ('protein serine/threonine kinase activity') is a part of another process (here: 'peptidyl-serine phosphorylation'), I noticed that the 'regulates' relation needs to be created between 'peptidyl-serine phosphorylation' and 'dynein intermediate chain binding', or the regulation_of GO annotations do not appear in what would be the GPAD output. (Please compare the screenshots below with the ones that I pasted in above under issue 1 header).

GO-CAM:
![screen shot 2017-11-13 at 11 58 56](https://user-images.githubusercontent.com/16541096/32726563-4ba792ac-c871-11e7-8561-fb57fe497f78.png)

Info that goes into the GPAD file:
![screen shot 2017-11-13 at 11 59 06](https://user-images.githubusercontent.com/16541096/32726574-536029aa-c871-11e7-9c84-8ab68b080799.png)

### Summary

So, overall my questions are:
1. Has Noctua started making regulation_of GO terms on the fly? Or what is the expected timeframe for this to be implemented? Should I go ahead and make my required regulation terms for now?
2. What is the most up-to-date documentation for capturing regulation in Noctua?
If I make the regulations terms mentioned above ([3](https://github.com/geneontology/go-ontology/issues/14361), [4](https://github.com/geneontology/go-ontology/issues/14360)), and then use the 'regulates' relation + process X in Noctua, will my output annotation be 'regulation of process X'? Or should I use the 'part of' relation with the new regulation terms, as the GO-CAM curation guidelines suggest? (But I suspect these are of date?).

Please advise!

Thanks,
Barbara

(optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:59dc728000000324)

**Comment by BarbaraCzub** [comment]
cc
@RLovering 
@rachhuntley
https://github.com/geneontology/go-annotation/issues/1690

**Comment by RLovering** [comment]
Hi Kimberly 

Please could you comment on the questions that Barbara has raised above?

Thanks

Ruth
@vanaukenk

**Comment by ValWood** [comment]
Hi,

Although I agree that if you create a "regulates" relationship a term should be created, dynein is *required* for microtubule anchoring, rather than 'regulating' (the kinase is regulating). The dynein complex moves the  components required for anchoring to the centrosome, and is definitely part_of the process.

val

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 
Kimberly is on vacation, I will try to answer: 


>    Has Noctua started making regulation_of GO terms on the fly? Or what is the expected timeframe for this to be implemented? Should I go ahead and make my required regulation terms for now?

This is not yet implemented, so best is to request the term until it is. 

>     What is the most up-to-date documentation for capturing regulation in Noctua?
The documentation on relations is here: http://wiki.geneontology.org/index.php/Annotation_Relations
but there isn't very much on 'regulates'. 

However, the relations for Molecular Function to Biological Process are: 

- part of
- causally upstream of or within, positive effect
- causally upstream of or within, negative effect
- causally upstream of, positive effect
- causally upstream of negative effect  


>    If I make the regulations terms mentioned above (3, 4), and then use the 'regulates' relation + process X in Noctua, will my output annotation be 'regulation of process X'? Or should I use the 'part of' relation with the new regulation terms, as the GO-CAM curation guidelines suggest? (But I suspect these are of date?).

I think you should use 'part of' relation with the new regulation terms, until we can do differently. 

(That is, if there really is regulation - see Val's comment). 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Thanks @pgaudet, I'll add the regulation term then.
Thanks @ValWood for your comment that only the kinase is regulating. I'll change the relation between 'dynein intermediate chain binding' and 'microtubule anchoring at centrosome' from 'regulates' to part_of and hopefully this will fix the output annotations.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Updated:
![Screenshot 2019-04-16 at 15 01 14](https://user-images.githubusercontent.com/16541096/56216020-941fa080-6058-11e9-9c38-e2e8c98916e1.png)
![Screenshot 2019-04-16 at 15 01 23](https://user-images.githubusercontent.com/16541096/56216091-b31e3280-6058-11e9-9ace-4988db4872fc.png)

But Noctua seems to have lost my ARUK-UCL attribution...

**Comment by ValWood** [comment]
I'm still confused by this:


    part of
    causally upstream of or within, positive effect
    causally upstream of or within, negative effect
    causally upstream of, positive effect
    causally upstream of negative effect

When I speak to @ukemi  he says that "causally upstream of" can be used for things way, way upstream (this is the feedback I got when querying GPs like this in matrix intersections).
If this is the case, this leaves us with no way to distinguish  "way, way upstream" from direct upstream regulation (i.e. the signalling that directly turns a process on). 

This is a problem.....because it means that we have not really improved from the previous situation where we could say "regulates" or "part of" except that we can now say "regulates OR part of" explicitly. 

I really don't think the meaning of "causally upstream of" is precise enough with regard to how far upstream it can be used. There will be huge problems later on unless this is made explicit somewhere. At the moment, it seems to me that there is actually a loss of specificity  compared to what we had previously because causally upstream is less stringent than "regulates" (however this depends who I speak to).

One thing is for sure. Everyone is not on the same page about this.

**Comment by pgaudet** [comment]
@ValWood The idea is if you are regulating, you would be 'part of' regulation of x, and not 'upstream from x'. 

Ideally we would move away from 'causally upstream of', this is *mostly* to deal with legacy annotations when experiments did not allow us to annotate very precisely (or when guidelines were a bit different). 

Pascale

**Comment by ValWood** [comment]
OK, I think I understand. So if something is causally upstream, but not regulating, which relationship would you use?

**Comment by pgaudet** [comment]
causally upstream of, positive effect
OR 
causally upstream of negative effect

dependent on the direction of the effect.

**Comment by ValWood** [comment]
So in this case  these are not the only relations to connect MF  to BP?

part of
causally upstream of or within, positive effect
causally upstream of or within, negative effect
causally upstream of, positive effect
causally upstream of negative effect

the regulation terms are additional?

**Comment by pgaudet** [comment]
There are no regulation relations - we should use 'part of regulation', AFAIK.

**Comment by ValWood** [comment]
OK so
protein kinase activity  has_input  BICD1 part_of regulation of microtubule anchoring at the centrosome 

(as above)

**Comment by pgaudet** [comment]
Sounds right to me.
