### ISSUE TITLE
MOD specific files no longer produced by 'export-lego-to-gpad-sparql' Jenkins job.

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/noctua-models#94]
The latest couple of 'export-lego-to-gpad-sparql' builds no longer show the MOD specific GPAD files. The last to have them was build [#547](http://build.berkeleybop.org/job/export-lego-to-gpad-sparql/547/artifact/legacy). 

Is this an expected result of some new QC checks, are the MOD specific files no longer supposed to be produced or is this a problem with the system?

**Comment by kltm** [comment]
@cmungall @dougli1sqrd Would you know that status of this job within the new pipeline?

**Comment by kltm** [comment]
@malcolmfisher103 There was apparently an issue with the reasoner that made a number of models inconsistent and may have severely reduced the output.
Also tagging on @balhoff

**Comment by dougli1sqrd** [comment]
Last time I heard about that job, it was still just operating in the old pipeline. Jim would probably know more.

**Comment by balhoff** [comment]
This looks like it's [back to normal now](https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/). However, unfortunately I don't know what happened in between. I'm not aware of any changes during this period.

**Comment by kltm** [comment]
Our best (and somewhat weak) guess at this point is that it was an error in an ontology import that got cleared. We'll try and look at better ways of monitoring issues like this.
(As well as get this bit of infrastructure into the main pipeline.)
@cmungall
