### ISSUE TITLE
Form view does not correspond to graph editor view -> (ref: gomodel:5ae3b0f600000604)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua-models#95]
Hi,

I have 5 annotations displayed in the form view:
![screen shot 2018-05-24 at 18 02 06](https://user-images.githubusercontent.com/16541096/40500418-98bdb6a0-5f7c-11e8-8a93-d1f6221c08ea.png)

But only 3 are displayed in the model:
![screen shot 2018-05-24 at 18 02 58](https://user-images.githubusercontent.com/16541096/40500460-b7b6a166-5f7c-11e8-8dcf-0061c1d24528.png)

Why is this? The 2 which are missing, do actually get displayed in the graph view for the first 1 second after switching to it, but then disappear.

And: how do I delete an annotation from the form view? (The fifth annotation is an identical copy of the fourth one. I added it only as a test, because the fourth annotation was not getting displayed in the graph view, and now I don't know how to remove it - it's not shown in 'Take a Tour').

Thanks,
Barbara

**Comment by vanaukenk** [comment]
Also, @tmushayahama and @lpalbou are working on adding Delete functionality to the form.  We want to make sure that when curators delete information using the form, the full implications are apparent, i.e. the potential effects on other relations and nodes in a given model.
Does deleting from the graph editor work okay for you in the meantime?

**Comment by kltm** [comment]
This issue was moved to geneontology/simple-annoton-editor#72
